config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'api/v1/sessions',
    registrations: 'api/v1/registrations'
  }


   namespace :api do
    namespace :v1 do
      resources :sts_runs, only: [:index,:show, :update]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sts_run.rb
class StsRun < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist


  def generate_authentication_token
    self.authentication_token = Devise.friendly_token
    save!
  end
end

app/controllers/api/v1/registrations_controller.rb
module Api
  module V1
    class RegistrationsController < Devise::RegistrationsController
    end
  end
end

app/controllers/api/v1/sessions_controller.rb
module Api
  module V1
    class SessionsController < Devise::SessionsController
    end
  end
end

app/controllers/api/v1/sts_runs_controller.rb
module Api
  module V1
    class StsRunsController < ApplicationController
      before_action :set_sts_run, only: %i[ show edit update destroy ]

      # GET /sts_runs or /sts_runs.json
      def index
        runs = StsRun.all
        render json: runs
      end

      # GET /sts_runs/1 or /sts_runs/1.json
      def show
        @sts_run = StsRun.find(params[:id])
        render json: @sts_run
      end

      # GET /sts_runs/new
      def new
        @sts_run = StsRun.new
      end

      # GET /sts_runs/1/edit
      def edit
        @sts_run = StsRun.find(params[:id])
      end

      # POST /sts_runs or /sts_runs.json
      def create
        @sts_run = StsRun.new(sts_run_params)

        respond_to do |format|
          if @sts_run.save
            format.html { redirect_to sts_run_url(@sts_run), notice: "Sts run was successfully created." }
            format.json { render :show, status: :created, location: @sts_run }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @sts_run.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /sts_runs/1 or /sts_runs/1.json
      # def update
      #   respond_to do |format|
      #     if @sts_run.update(sts_run_params)
      #       format.html { redirect_to sts_run_params(@sts_run), notice: "Sts run was successfully updated." }
      #       format.json { render :show, status: :ok, location: @sts_run }
      #     else
      #       format.html { render :edit, status: :unprocessable_entity }
      #       format.json { render json: @sts_run.errors, status: :unprocessable_entity }
      #     end
      #   end
      # end
      def update
        @sts_run = StsRun.find(params[:id])

        if @sts_run.update(sts_run_params)
          render json: @sts_run, status: :ok
        else
          render json: @sts_run.errors, status: :unprocessable_entity
        end
      end

      # DELETE /sts_runs/1 or /sts_runs/1.json
      def destroy
        @sts_run.destroy

        respond_to do |format|
          format.html { redirect_to sts_runs_url, notice: "Sts run was successfully destroyed." }
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_sts_run
          @sts_run = StsRun.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def sts_run_params
          params.require(:sts_run).permit(:notes)
        end
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sts_runs_controller.rb
class StsRunsController < ApplicationController
  before_action :set_sts_run, only: %i[ show edit update destroy ]

  # GET /sts_runs or /sts_runs.json
  def index
    @sts_runs = StsRun.all
  end

  # GET /sts_runs/1 or /sts_runs/1.json
  def show
    @sts_run = StsRun.find(params[:id])
  end

  # GET /sts_runs/new
  def new
    @sts_run = StsRun.new
  end

  # GET /sts_runs/1/edit
  def edit
    @sts_run = StsRun.find(params[:id])
  end

  # POST /sts_runs or /sts_runs.json
  def create
    @sts_run = StsRun.new(sts_run_params)

    respond_to do |format|
      if @sts_run.save
        format.html { redirect_to sts_run_url(@sts_run), notice: "Sts run was successfully created." }
        format.json { render :show, status: :created, location: @sts_run }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sts_run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sts_runs/1 or /sts_runs/1.json
  def update
    respond_to do |format|
      if @sts_run.update(sts_run_params)
        format.html { redirect_to sts_run_url(@sts_run), notice: "Sts run was successfully updated." }
        format.json { render :show, status: :ok, location: @sts_run }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sts_run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sts_runs/1 or /sts_runs/1.json
  def destroy
    @sts_run.destroy

    respond_to do |format|
      format.html { redirect_to sts_runs_url, notice: "Sts run was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sts_run
      @sts_run = StsRun.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sts_run_params
      params.require(:sts_run).permit(:character, :floor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sts_runs_helper.rb
module StsRunsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>STSTrackApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sts_runs/_form.html.erb
<%= form_with(model: sts_run) do |form| %>
  <% if sts_run.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sts_run.errors.count, "error") %> prohibited this sts_run from being saved:</h2>

      <ul>
        <% sts_run.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :character, style: "display: block" %>
    <%= form.text_field :character %>
  </div>

  <div>
    <%= form.label :floor, style: "display: block" %>
    <%= form.number_field :floor %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sts_runs/_sts_run.html.erb
<div id="<%= dom_id sts_run %>">
  <p>
    <strong>Character:</strong>
    <%= sts_run.character %>
  </p>

  <p>
    <strong>Ascension:</strong>
    <%= sts_run.ascension %>
  </p>

  <p>
    <strong>Seed:</strong>
    <%= sts_run.seed %>
  </p>

  <p>
    <strong>Floor:</strong>
    <%= sts_run.floor %>
  </p>

  <p>
    <strong>Victory:</strong>
    <%= sts_run.victory %>
  </p>

  <p>
    <strong>Heart Kill:</strong>
    <%= sts_run.heart_kill %>
  </p>

  <p>
    <strong>Killed By:</strong>
    <%= sts_run.killed_by %>
  </p>

  <p>
    <strong>Gold:</strong>
    <%= sts_run.gold %>
  </p>

  <p>
    <strong>Max HP:</strong>
    <%= sts_run.max_hp %>
  </p>

  <p>
    <strong>Local Time:</strong>
    <%= sts_run.local_time %>
  </p>

  <p>
    <strong>Damage Taken:</strong>
    <%= sts_run.damage_taken %>
  </p>

  <p>
    <strong>Master Deck:</strong>
    <%= sts_run.master_deck %>
  </p>

  <p>
    <strong>Relics:</strong>
    <%= sts_run.relics %>
  </p>
</div>

app/views/sts_runs/edit.html.erb
<h1>Editing sts run</h1>

<%= render "form", sts_run: @sts_run %>

<br>

<div>
  <%= link_to "Show this sts run", @sts_run %> |
  <%= link_to "Back to sts runs", sts_runs_path %>
</div>

app/views/sts_runs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Slay the Spire Run Log</h1>

<div id="sts_runs">
  <% @sts_runs.order(local_time: :desc).each do |sts_run| %>
    <%# <%= render sts_run %>
    <p>
      <strong>
        <%= sts_run.character == 'THE_SILENT'? 'SILENT':sts_run.character%>
      </strong>
      |
      <strong>Ascension:</strong>
      <%= sts_run.ascension %>
      |
    <% if sts_run.victory %>
        <strong>Victory
      <% if sts_run.heart_kill %>
          Against the Heart
      <% end %>
        </strong>
      </p>
    <% end %>


    <% if !sts_run.victory %>
        <strong>Killed By:</strong>
        <%= sts_run.killed_by %>
    <% end %>
    <p>
      <%= link_to "Show this sts run", sts_run %>
    </p>
    <br/>
  <% end %>

</div>

<%= link_to "New sts run", new_sts_run_path %>

app/views/sts_runs/new.html.erb
<h1>New sts run</h1>

<%= render "form", sts_run: @sts_run %>

<br>

<div>
  <%= link_to "Back to sts runs", sts_runs_path %>
</div>

app/views/sts_runs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sts_run %>

<div>
  <%= link_to "Edit this sts run", edit_sts_run_path(@sts_run) %> |
  <%= link_to "Back to sts runs", sts_runs_path %>

  <%= button_to "Destroy this sts run", @sts_run, method: :delete %>
</div>